#!/usr/bin/env python3
"""Regenerate log.txt with last-update times for the 3 tracked deliverables.

Called by .github/workflows/weglot-sync.yml and .github/workflows/update-sitemap-llms.yml
as part of the commit step. For files changed in this run (passed via the
CHANGED env var — a space-separated list from `git diff --cached --name-only`),
the current GMT+3 time is used. For other tracked files, `git log -1 --format=%cI`
returns the most recent commit timestamp touching them.

The Weglot upload-required signal is derived from the literal state of root
weglot.csv at the moment this script runs:
- File absent OR empty (or header-only) → cleared, no upload needed
- File present with N data rows → N pending, upload required

No side effects at import time. Run locally with CHANGED="" to seed log.txt
from pure git history.
"""
from __future__ import annotations

import os
import pathlib
import subprocess
import sys
from datetime import datetime, timedelta, timezone

TRACKED = ("sitemap.xml", "llms.txt", "weglot.csv")
DASHBOARD = "https://dashboard.weglot.com/workspaces/w-6bc645f5ad/projects/cel/settings/exclusions"
CSV_URL = "https://sitemap.englishcollege.com/weglot.csv"

# Display timezone. Turkey is fixed GMT+3 year-round (no DST since 2016),
# so a plain fixed offset is correct and avoids the tzdata dependency.
TZ_DISPLAY = timezone(timedelta(hours=3))


def git_last_touched(path: str) -> str:
    """Return 'YYYY-MM-DD HH:MM GMT+3' of last commit touching path, or 'never'."""
    try:
        r = subprocess.run(
            ["git", "log", "-1", "--format=%cI", "--", path],
            capture_output=True,
            text=True,
            check=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return "never"
    raw = r.stdout.strip()
    if not raw:
        return "never"
    try:
        dt = datetime.fromisoformat(raw)
    except ValueError:
        return "never"
    return dt.astimezone(TZ_DISPLAY).strftime("%Y-%m-%d %H:%M GMT+3")


def count_pending_weglot_entries() -> int:
    """Count data rows in root weglot.csv. 0 means no upload needed."""
    p = pathlib.Path("weglot.csv")
    if not p.exists():
        return 0
    try:
        text = p.read_text(encoding="utf-8")
    except OSError:
        return 0
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if not lines:
        return 0
    # Treat first row as header if it matches Weglot CSV format.
    # The actual header is "id;type;value;languages;language_button_displayed;exclusion_behavior".
    first_lower = lines[0].lower()
    if "exclusion_behavior" in first_lower or first_lower.startswith("id;"):
        return max(0, len(lines) - 1)
    return len(lines)


def build_entries(now: str, changed: set[str]) -> dict[str, str]:
    """Build {filename: 'timestamp suffix'} for every TRACKED file."""
    out: dict[str, str] = {}
    for name in TRACKED:
        is_changing = name in changed or (name == "weglot.csv" and "data/weglot.csv" in changed)
        ts = now if is_changing else git_last_touched(name)
        out[name] = ts
    pending = count_pending_weglot_entries()
    if pending == 1:
        suffix = "[1 pending entry — UPLOAD NEEDED]"
    elif pending > 1:
        suffix = f"[{pending} pending entries — UPLOAD NEEDED]"
    else:
        suffix = "[cleared — no upload needed]"
    out["weglot.csv"] = f"{out['weglot.csv']}  {suffix}"
    return out


def render(entries: dict[str, str], pending: int) -> str:
    lines = ["Last updated (GMT+3 — auto-generated by GitHub Actions):", ""]
    for name in TRACKED:
        lines.append(f"  {name:<12}  {entries[name]}")
    lines.append("")
    if pending > 0:
        lines.append("Upload to Weglot: REQUIRED")
        lines.append(f"  Download: {CSV_URL}")
        lines.append(f"  Dashboard: {DASHBOARD}")
    else:
        lines.append("Upload to Weglot: NOT REQUIRED")
    return "\n".join(lines) + "\n"


def main() -> int:
    changed = set(os.environ.get("CHANGED", "").split())
    now = datetime.now(TZ_DISPLAY).strftime("%Y-%m-%d %H:%M GMT+3")
    entries = build_entries(now, changed)
    pending = count_pending_weglot_entries()
    pathlib.Path("log.txt").write_text(render(entries, pending), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
